debug: false

spring:
  application:
    name: guess-user
  http:
    encoding:
      charset: utf-8
      force: true
  # 启用AOP
  aop:
    auto: true
    proxy-target-class: false
  # 控制台以ANSI彩色输出
  output:
    ansi:
      enabled: ALWAYS
  # 包含其它配置文件
  profiles:
    include: cloud,config,properties,config-custom,config-midderware

# LogBack配置文件
logging:
  config: classpath:logback-spring.xml