# 服务端口
server:
  port: 51112

eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.0.74:51200/eureka/ # 注册中心

spring:
  datasource:
    master:
      url: jdbc:mysql://192.168.1.71:3306/demo_bc?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: bc
      password: bc
    slave:
      url: jdbc:mysql://192.168.1.70:3306/demo_bc?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: bc
      password: bc
  redis:
     database: 0   # Redis数据库索引（默认为0）
     host: 192.168.0.74
     port: 8888
     password: 123456

redisson:
    database: 0
    url: redis://192.168.0.74:8888
    password: 123456

# 短信
sms:
  voice:
    url:
    account:
    password:
    key:
    showNumber:
  text:
    url: http://smssh1.253.com/msg/send/json
    account: N213554_N7573544
    password: 5mYiowrqORea1f

# 代理配置
web:
  common:
    code: 9999
    level: 3