# 服务端口
server:
  port: 51112

# 注册中心
eureka:
  client:
    serviceUrl:
      defaultZone: http://dev.eureka.durian.com:51100/eureka/



spring:
  datasource:
    master:
      url: jdbc:mysql://192.168.0.71:3306/dev_guess?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true
      username: dev
      password: dev
    slave:
      url: jdbc:mysql://192.168.0.70:3306/dev_guess?useUnicode=true&characterEncoding=UTF-8&useSSL=false&allowMultiQueries=true
      username: dev
      password: dev
  redis:
    database: 1   # Redis数据库索引（默认为0）
    host: 192.168.0.25   # Redis服务器连接端口
    port: 8899
    password: 123456

redisson:
    database: 1
    url: redis://192.168.0.25:8899
    password: 123456


# 短信
sms:
  voice:
    url:
    account:
    password:
    key:
    showNumber:
  text:
    url: http://smssh1.253.com/msg/send/json
    account: N213554_N7573544
    password: 5mYiowrqORea1f