spring:
  datasource:
    master:
      url: jdbc:mysql://192.168.1.71:3306/dev_guess?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: dev
      password: dev
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.jdbc.Driver
      connectionProperties: config.decrypt=true
      filters: stat,wall
      maxActive: 50
      initialSize: 1
      maxWait: 60000
      minIdle: 5
      timeBetweenEvictionRunsMillis: 30000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
    slave:
      url: jdbc:mysql://192.168.1.70:3306/dev_guess?useUnicode=true&characterEncoding=UTF-8&useSSL=false
      username: dev
      password: dev
      # 使用druid数据源
      type: com.alibaba.druid.pool.DruidDataSource
      driverClassName: com.mysql.jdbc.Driver
      connectionProperties: config.decrypt=true
      filters: stat,wall
      maxActive: 50
      initialSize: 1
      maxWait: 60000
      minIdle: 5
      timeBetweenEvictionRunsMillis: 30000
      minEvictableIdleTimeMillis: 300000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false
      poolPreparedStatements: true
      maxOpenPreparedStatements: 20
  # redis配置
  redis:
    database: 0   # Redis数据库索引（默认为0）
    host: 192.168.1.15   # Redis服务器连接端口
    port: 9648
    password: 123456
    timeout: 0  # 连接超时时间（毫秒）
    # 连接池配置
    pool:
      max-active: 1024  # 连接池最大连接数（使用负值表示没有限制）
      max-wait: 1000  # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-idle: 20  # 连接池中的最大空闲连接
      min-idle: 0  # 连接池中的最小空闲连接
  rabbitmq:
    host: 192.168.1.15
    port: 5672
    username: guest
    password: guest

redisson:
    url: redis://192.168.1.15:9648
    password: 123456